import { defineStore } from "pinia"
import { Coords, HEADING, ResourceTable, Town, TownStore } from "../types/interfaces.ts"
import { albatrossParams, pelicanParams, seagullParams, whaleParams } from "../configs/gameplay.config.ts"

export const useTown = defineStore("town", {
    state: (): TownStore => ({
        currentTownId: "start-01",
        coords: {
            x: 7168,
            y: 7672,
        },
        towns: [
            {
                id: "start-01",
                name: "Брайвиль",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: seagullParams.name,
                        description: seagullParams.description,
                        velocity: seagullParams.velocity,
                        angularVelocity: seagullParams.angularVelocity,
                        damage: seagullParams.damage,
                        type: "seagull",
                        maxHealth: seagullParams.maxHealth,
                        currentHealth: seagullParams.currentHealth,
                        maxFuel: seagullParams.maxFuel,
                        currentFuel: seagullParams.maxFuel,
                        price: seagullParams.price,
                        repairPrice: seagullParams.repairPrice,
                    },
                    {
                        id: 5,
                        name: albatrossParams.name,
                        description: albatrossParams.description,
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 300,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 13,
                        optima: 300,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 13,
                        [HEADING.MAX_VALUE]: 600,
                        minBuyPrice: 8,
                        minSellPrice: 12,
                        maxBuyPrice: 12,
                        maxSellPrice: 15,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 400,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 400,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 800,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 4,
                        [HEADING.SELL_PRICE]: 5,
                        optima: 250,
                        optimaBuyPrice: 4,
                        optimaSellPrice: 5,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 4,
                        maxBuyPrice: 5,
                        maxSellPrice: 6,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 250,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 50,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 50,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description:
                    '<p><b style="color:#4CAF50;"><strong>Брайвиль</strong></b> — город храбрых авантюристов. Он стал первым поселением людей в Королевстве Зеленых Островов. Именно здесь изобрели корабль <b style="color:#6658cd;"><strong>“Храбрая чайка”</strong></b>, с помощью которого стали заселять соседние острова.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Благодаря благоприятному климату региона, <b style="color:#4CAF50;"><strong>Брайвиль</strong></b> преуспел в выращивании таких сельскохозяйственных культур, как <b style="color:#4CAF50;"><strong>сахарный тростник</strong></b>, <b style="color:#B71C1C;"><strong>пряности</strong></b> и <b style="color:#FF6F00;"><strong>зерно</strong></b>. В городе изготавливают ткани из <b style="color:#9CCC65;"><strong>хлопка</strong></b> и <b style="color:#64DD17;"><strong>конопли</strong></b>. Поэтому эти товары здесь всегда можно приобрести по выгодной цене.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p><b style="color:#FFB300;"><strong>Кукурузу</strong></b> в <b style="color:#4CAF50;"><strong>Брайвиле</strong></b> не выращивают, ее предпочитают закупать у <b style="color:#4CAF50;"><strong>Дальнего берега</strong></b>.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Своего производства и добычи промышленных товаров в <b style="color:#4CAF50;"><strong>Брайвиле</strong></b> нет. Поэтому <b style="color:#3E2723;"><strong>порох</strong></b>, <b style="color:#607D8B;"><strong>сталь</strong></b> и <b style="color:#000000;"><strong>уголь</strong></b> городу приходится закупать из дальних городов. Каждый караван с <b style="color:#E65100;"><strong>Южного Кита</strong></b> всегда встречается с большой радостью.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Ремесленники, которые ценят роскошные товары, такие как <b style="color:#D50000;"><strong>шелк</strong></b> и <b style="color:#BDBDBD;"><strong>слоновая кость</strong></b>, ждут корабли, прилетающие из <b style="color:#BF360C;"><strong>Нордвиля</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Между <b style="color:#4CAF50;"><strong>Брайвилем</strong></b> и <b style="color:#4CAF50;"><strong>Мидлгардом</strong></b> постоянно идет торговля. Хотя корабли модели <b style="color:#23628e;"><strong>“Храбрый альбатрос”</strong></b> отлично справляются с перевозками, они недостаточно мощные в бою, чтобы отпугивать <b style="color:#474c5e;"><strong>пиратов</strong></b>, которые на этом маршруте встречаются достаточно часто.&nbsp;</p>\n',
            },
            {
                id: "start-02",
                name: "Дальний берег",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: seagullParams.name,
                        description: seagullParams.description,
                        velocity: seagullParams.velocity,
                        angularVelocity: seagullParams.angularVelocity,
                        damage: seagullParams.damage,
                        type: "seagull",
                        maxHealth: seagullParams.maxHealth,
                        currentHealth: seagullParams.currentHealth,
                        maxFuel: seagullParams.maxFuel,
                        currentFuel: seagullParams.maxFuel,
                        price: seagullParams.price,
                        repairPrice: seagullParams.repairPrice,
                    },
                    {
                        id: 5,
                        name: albatrossParams.name,
                        description: albatrossParams.description,
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 300,
                        [HEADING.BUY_PRICE]: 18,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 300,
                        optimaBuyPrice: 18,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 600,
                        minBuyPrice: 16,
                        minSellPrice: 24,
                        maxBuyPrice: 20,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 33,
                        optima: 250,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 33,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 29,
                        minSellPrice: 32,
                        maxBuyPrice: 36,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 4,
                        [HEADING.SELL_PRICE]: 5,
                        optima: 250,
                        optimaBuyPrice: 4,
                        optimaSellPrice: 5,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 4,
                        maxBuyPrice: 5,
                        maxSellPrice: 6,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 250,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 50,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 50,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description:
                    '<p><b style="color:#4CAF50;"><strong>Дальний Берег</strong></b> — город, находящийся на самом краю Королевства Зеленых Островов. Этот остров был заселен вторым после <b style="color:#4CAF50;"><strong>Брайвиля</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Как и <b style="color:#4CAF50;"><strong>Брайвиль</strong></b>, <b style="color:#4CAF50;"><strong>Дальний Берег</strong></b> специализируется на изготовлении тканей из <b style="color:#9CCC65;"><strong>хлопка</strong></b> и <b style="color:#64DD17;"><strong>конопли</strong></b>. Однако такие культуры, как <b style="color:#4CAF50;"><strong>сахарный тростник</strong></b>, <b style="color:#B71C1C;"><strong>пряности</strong></b> и <b style="color:#FF6F00;"><strong>зерно</strong></b>, выращивают не так много, как в соседнем городе, поэтому эти товары здесь дороже.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p><b style="color:#FFB300;"><strong>Кукурузу</strong></b> на <b style="color:#4CAF50;"><strong>Дальнем Берегу</strong></b> выращивают очень много. Так много, что продают большой излишек <b style="color:#4CAF50;"><strong>Брайвилю</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Своего производства и добычи промышленных товаров на <b style="color:#4CAF50;"><strong>Дальнем Берегу</strong></b> нет. Как и соседний город, <b style="color:#3E2723;"><strong>порох</strong></b>, <b style="color:#607D8B;"><strong>сталь</strong></b> и <b style="color:#000000;"><strong>уголь</strong></b> <b style="color:#4CAF50;"><strong>Дальний Берег</strong></b> закупает из дальних городов, в первую очередь из <b style="color:#E65100;"><strong>Южного Кита</strong></b>. <b style="color:#D50000;"><strong>Шелк</strong></b> и <b style="color:#BDBDBD;"><strong>слоновую кость</strong></b> — из <b style="color:#BF360C;"><strong>Нордвиля</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Из-за отдаленного расположения <b style="color:#474c5e;"><strong>пираты</strong></b> не появляются рядом с городом. Но отлетать далеко от города, кроме как в направлении к <b style="color:#4CAF50;"><strong>Брайвилю</strong></b>, все же не стоит.</p>\n',
            },
            {
                id: "middle",
                name: "Мидлгард",
                color: "green",
                ships: [
                    {
                        id: 5,
                        name: albatrossParams.name,
                        description: albatrossParams.description,
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                    {
                        id: 6,
                        name: pelicanParams.name,
                        description: pelicanParams.description,
                        velocity: pelicanParams.velocity,
                        angularVelocity: pelicanParams.angularVelocity,
                        damage: pelicanParams.damage,
                        type: "pelican",
                        maxHealth: pelicanParams.maxHealth,
                        currentHealth: pelicanParams.currentHealth,
                        maxFuel: pelicanParams.maxFuel,
                        currentFuel: pelicanParams.currentFuel,
                        price: pelicanParams.price,
                        repairPrice: pelicanParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 13,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 13,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 8,
                        minSellPrice: 12,
                        maxBuyPrice: 12,
                        maxSellPrice: 15,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 500,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 700,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 700,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 1400,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 600,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 600,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 1200,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 11,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 9,
                        minSellPrice: 10,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 16,
                        optima: 500,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 14,
                        minSellPrice: 19,
                        maxBuyPrice: 16,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 500,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 500,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 500,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 100,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 100,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description:
                    '<p><b style="color:#4CAF50;"><strong>Мидлгард</strong></b> является столицей Королевства Зеленых Островов и крупнейшим в нем городом. После долгих скитаний по небесным островам первые поселенцы попали на остров огромных размеров, покрытый лесами и горами. Есть теория о том, что этот остров был частью огромного континента, который взмыл в небо после Катаклизма, а затем раскололся на отдельные острова. Судя по всему, остальные острова откололись именно от <b style="color:#4CAF50;"><strong>Мидлгарда</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Город является главным поставщиком всех сельскохозяйственных культур на Небесах Трех Дорог. <b style="color:#4CAF50;"><strong>Сахарный тростник</strong></b>, <b style="color:#B71C1C;"><strong>пряности</strong></b>, <b style="color:#FF6F00;"><strong>зерно</strong></b> и <b style="color:#FFB300;"><strong>кукуруза</strong></b> здесь всегда в изобилии и стоят дешево.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Только <b style="color:#9CCC65;"><strong>хлопок</strong></b> и <b style="color:#64DD17;"><strong>конопля</strong></b> из-за более южного расположения здесь растут плохо. Город закупает их у <b style="color:#4CAF50;"><strong>Брайвиля</strong></b> и <b style="color:#4CAF50;"><strong>Дальнего Берега</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Как и все королевство, промышленное сырье и товары, такие как <b style="color:#3E2723;"><strong>порох</strong></b>, <b style="color:#607D8B;"><strong>сталь</strong></b> и <b style="color:#000000;"><strong>уголь</strong></b>, город закупает из <b style="color:#E65100;"><strong>Южного Кита</strong></b>.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Для торговли с <b style="color:#BF360C;"><strong>Нордвилем</strong></b>, у которого город покупает <b style="color:#D50000;"><strong>шелк</strong></b> и <b style="color:#BDBDBD;"><strong>слоновую кость</strong></b>, верфи города закупают корабли <b style="color:#febe0c;"><strong>“Золотой Пеликан”</strong></b>. На этих кораблях можно добраться также и до <b style="color:#E65100;"><strong>Южного Кита</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Флот королевства состоит в основном из кораблей модели <b style="color:#23628e;"><strong>“Храбрый альбатрос”</strong></b>, которая не очень подходит для боя с <b style="color:#474c5e;"><strong>пиратами</strong></b>. Поэтому как рядом с городом, так и на пути к <b style="color:#4CAF50;"><strong>Брайвилю</strong></b>, их достаточно много.</p>\n',
            },
            {
                id: "final-01",
                name: "Нордвиль",
                color: "deep-orange",
                ships: [
                    {
                        id: 6,
                        name: pelicanParams.name,
                        description: pelicanParams.description,
                        velocity: pelicanParams.velocity,
                        angularVelocity: pelicanParams.angularVelocity,
                        damage: pelicanParams.damage,
                        type: "pelican",
                        maxHealth: pelicanParams.maxHealth,
                        currentHealth: pelicanParams.currentHealth,
                        maxFuel: pelicanParams.maxFuel,
                        currentFuel: pelicanParams.currentFuel,
                        price: pelicanParams.price,
                        repairPrice: pelicanParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 1000,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 18,
                        minSellPrice: 22,
                        maxBuyPrice: 22,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 25,
                        [HEADING.SELL_PRICE]: 35,
                        optima: 1000,
                        optimaBuyPrice: 25,
                        optimaSellPrice: 35,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 20,
                        minSellPrice: 30,
                        maxBuyPrice: 30,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 22,
                        optima: 500,
                        optimaBuyPrice: 9,
                        optimaSellPrice: 10,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 5,
                        minSellPrice: 6,
                        maxBuyPrice: 10,
                        maxSellPrice: 11,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 1200,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1200,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 2400,
                        minBuyPrice: 12,
                        minSellPrice: 16,
                        maxBuyPrice: 15,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 11,
                        optima: 1000,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 9,
                        minSellPrice: 10,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 1000,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 1000,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 1000,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1000,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 1000,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 40,
                        optima: 250,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 40,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 25,
                        minSellPrice: 35,
                        maxBuyPrice: 35,
                        maxSellPrice: 45,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 15,
                        maxBuyPrice: 15,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                ],
                description:
                    '<p><b style="color:#BF360C;"><strong>Нордвиль</strong></b> — единственный город, расположенный в регионе Глиняных гор. Из-за своей удаленности на севере и сурового климата, это был последний город, который заселили в Небесах Трех Дорог. Но несмотря на то, что <b style="color:#BF360C;"><strong>Нордвиль</strong></b> является самым молодым поселением, он развивается достаточно быстро.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Как уже было сказано, климат в <b style="color:#BF360C;"><strong>Нордвиле</strong></b> очень суровый, поэтому выращивать здесь сельскохозяйственные культуры очень сложно. <b style="color:#4CAF50;"><strong>Сахарный тростник</strong></b>, <b style="color:#FF6F00;"><strong>зерно</strong></b> и <b style="color:#FFB300;"><strong>кукурузу</strong></b> город закупает у <b style="color:#4CAF50;"><strong>Мидлгарда</strong></b>. <b style="color:#9CCC65;"><strong>Хлопок</strong></b> приходится везти аж из самого <b style="color:#4CAF50;"><strong>Брайвиля</strong></b>.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Каким-то чудом в городе научились выращивать <b style="color:#B71C1C;"><strong>пряности</strong></b> и <b style="color:#64DD17;"><strong>коноплю</strong></b>. Как фермерам <b style="color:#BF360C;"><strong>Нордвиля</strong></b> удается получать большие урожаи этих культур, никто не знает, а те не раскрывают своих секретов.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>В горах <b style="color:#BF360C;"><strong>Нордвиля</strong></b> было найдено большое количество скелетов мамонтов. Эти древние существа населяли землю задолго до Катаклизма. <b style="color:#BF360C;"><strong>Нордвиль</strong></b> стал главным поставщиком как изделий из <b style="color:#BDBDBD;"><strong>слоновой кости</strong></b>, так и самих костей.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>В лесах <b style="color:#BF360C;"><strong>Нордвиля</strong></b> обитает большое количество гусениц-шелкопрядов. Цены на <b style="color:#D50000;"><strong>шелк</strong></b> здесь самые низкие в Небесах Трех Дорог.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>В городе промышленность находится на ранней стадии развития, ведь поселение очень молодое. <b style="color:#3E2723;"><strong>Порох</strong></b>, <b style="color:#607D8B;"><strong>сталь</strong></b> и <b style="color:#000000;"><strong>уголь</strong></b> город пока вынужден закупать из <b style="color:#E65100;"><strong>Южного Кита</strong></b>.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Для торговли с другими городами инженеры <b style="color:#BF360C;"><strong>Нордвиля</strong></b> создали мощный корабль модели <b style="color:#febe0c;"><strong>“Золотой пеликан”</strong></b>. На этом корабле можно добраться в любой уголок в Небесах Трех Дорог. По этой причине <b style="color:#474c5e;"><strong>пираты</strong></b> держатся от Глиняных гор на почтительном расстоянии.&nbsp;</p>\n',
            },
            {
                id: "final-02",
                name: "Южный кит",
                color: "orange",
                ships: [
                    {
                        id: 7,
                        name: whaleParams.name,
                        description: whaleParams.description,
                        velocity: whaleParams.velocity,
                        angularVelocity: whaleParams.angularVelocity,
                        damage: whaleParams.damage,
                        type: "whale",
                        maxHealth: whaleParams.maxHealth,
                        currentHealth: whaleParams.currentHealth,
                        maxFuel: whaleParams.maxFuel,
                        currentFuel: whaleParams.currentFuel,
                        price: whaleParams.price,
                        repairPrice: 8,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 1000,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 18,
                        minSellPrice: 22,
                        maxBuyPrice: 22,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 25,
                        [HEADING.SELL_PRICE]: 35,
                        optima: 1000,
                        optimaBuyPrice: 25,
                        optimaSellPrice: 35,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 20,
                        minSellPrice: 30,
                        maxBuyPrice: 30,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 33,
                        optima: 1000,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 33,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 29,
                        minSellPrice: 32,
                        maxBuyPrice: 36,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 1200,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1200,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 2400,
                        minBuyPrice: 12,
                        minSellPrice: 16,
                        maxBuyPrice: 15,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 44,
                        optima: 500,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 44,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 32,
                        minSellPrice: 40,
                        maxBuyPrice: 44,
                        maxSellPrice: 48,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 750,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 16,
                        optima: 750,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 1500,
                        minBuyPrice: 14,
                        minSellPrice: 19,
                        maxBuyPrice: 16,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 750,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 750,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 1500,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 1500,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 1500,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 3000,
                        minBuyPrice: 10,
                        minSellPrice: 19,
                        maxBuyPrice: 20,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 2000,
                        [HEADING.BUY_PRICE]: 6,
                        [HEADING.SELL_PRICE]: 9,
                        optima: 2000,
                        optimaBuyPrice: 6,
                        optimaSellPrice: 9,
                        [HEADING.MAX_VALUE]: 4000,
                        minBuyPrice: 4,
                        minSellPrice: 7,
                        maxBuyPrice: 7,
                        maxSellPrice: 11,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 1500,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 1500,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 3000,
                        minBuyPrice: 18,
                        minSellPrice: 24,
                        maxBuyPrice: 24,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 100,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 100,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description:
                    '<p><b style="color:#E65100;"><strong>Южный Кит</strong></b> — единственное поселение на Лунной дороге. Город стал одним из последних поселений в Небесах Трех Дорог. Название город получил благодаря своей форме, напоминающей гигантскую рыбу. Видимо, по этой причине здесь возник культ поклонения Небесным Китам, мифическим созданиям, якобы летающим среди островов.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>В Хвостовом хребте, так называются горы в южной части города, были обнаружены богатые залежи различных полезных ископаемых. <b style="color:#E65100;"><strong>Южный Кит</strong></b> является главным поставщиком <b style="color:#3E2723;"><strong>пороха</strong></b>, <b style="color:#607D8B;"><strong>стали</strong></b> и <b style="color:#000000;"><strong>угля</strong></b> во всех городах, выполняя роль промышленного центра.</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Все остальные товары город закупает со всего региона. Поскольку на песчаных островах Лунной дороги вообще не растут деревья, <b style="color:#795548;"><strong>древесина</strong></b> в <b style="color:#E65100;"><strong>Южном</strong></b> <b style="color:#E65100;"><strong>Ките</strong></b> — один из самых дорогих товаров. Здесь она стоит дороже, чем в любом другом городе.&nbsp;</p>\n' +
                    "<p>&nbsp;</p>\n" +
                    '<p>Благодаря развитой промышленности инженеры <b style="color:#E65100;"><strong>Южного Кита</strong></b> смогли создать самый мощный корабль в районе — модель <b style="color:#325ceb;"><strong>Небесный Кит</strong></b>. Этот шедевр инженерной мысли превосходит любой корабль. По этой причине <b style="color:#474c5e;"><strong>пираты</strong></b> даже близко не подлетают к Лунной дороге.</p>\n',
            },
        ],
        isShowSinkAlert: false,
    }),
    getters: {
        currentTown: (state): Town => {
            return state.towns.find((town) => town.id === state.currentTownId) as Town
        },
    },
    actions: {
        setTown(name: string): void {
            this.currentTownId = name
        },
        setCoords(coords: Coords): void {
            this.coords = coords
        },
        setShowSinkAlert(value: boolean) {
            this.isShowSinkAlert = value
        },
        decreaseCurrentTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] -= amount
        },
        increaseCurrentTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] += amount
        },
        increaseTownResource(townId: string, key: string, amount: number) {
            const town = this.towns.find((town) => town.id === townId) as Town
            const resource = town.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] += amount
            resource.isGrow = true
        },
        decreaseTownResource(townId: string, key: string, amount: number) {
            const town = this.towns.find((town) => town.id === townId) as Town
            const resource = town.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] -= amount
            resource.isGrow = resource[HEADING.VALUE] <= resource.optima
        },
        calculatePrice(resource: ResourceTable) {
            const difference = resource.optima - resource[HEADING.VALUE]
            const percentValue = difference / (resource.optima / 100)
            const percentBuyPrice = resource.optimaBuyPrice / 100
            const percentSellPrice = resource.optimaSellPrice / 100
            let newBuyPrice = resource[HEADING.BUY_PRICE]
            let newSellPrice = resource[HEADING.BUY_PRICE]
            if (resource[HEADING.VALUE] < resource.optima) {
                newBuyPrice = Math.floor(resource.optimaBuyPrice + Math.abs(percentValue) * percentBuyPrice)
                newSellPrice = Math.floor(resource.optimaSellPrice + Math.abs(percentValue) * percentSellPrice)
            } else {
                newBuyPrice = Math.floor(resource.optimaBuyPrice - Math.abs(percentValue) * percentBuyPrice)
                newSellPrice = Math.floor(resource.optimaSellPrice - Math.abs(percentValue) * percentSellPrice)
            }

            if (newBuyPrice > resource.maxBuyPrice) {
                resource[HEADING.BUY_PRICE] = resource.maxBuyPrice
            } else if (newBuyPrice < resource.minBuyPrice) {
                resource[HEADING.BUY_PRICE] = resource.minBuyPrice
            } else {
                resource[HEADING.BUY_PRICE] = newBuyPrice
            }

            if (newSellPrice > resource.maxSellPrice) {
                resource[HEADING.SELL_PRICE] = resource.maxSellPrice
            } else if (newSellPrice < resource.minSellPrice) {
                resource[HEADING.SELL_PRICE] = resource.minSellPrice
            } else {
                resource[HEADING.SELL_PRICE] = newSellPrice
            }
        },
    },
})
