import { defineStore } from "pinia"
import { Coords, HEADING, ResourceTable, Town, TownStore } from "../types/interfaces.ts"
import { albatrossParams, pelicanParams, seagullParams, whaleParams } from "../configs/gameplay.config.ts"

export const useTown = defineStore("town", {
    state: (): TownStore => ({
        currentTownId: "start-01",
        coords: {
            x: 7168,
            y: 7672,
        },
        towns: [
            {
                id: "start-01",
                name: "Брайвиль",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: "Хромая чайка",
                        velocity: seagullParams.velocity,
                        angularVelocity: seagullParams.angularVelocity,
                        damage: seagullParams.damage,
                        type: "seagull",
                        maxHealth: seagullParams.maxHealth,
                        currentHealth: seagullParams.currentHealth,
                        maxFuel: seagullParams.maxFuel,
                        currentFuel: seagullParams.maxFuel,
                        price: seagullParams.price,
                        repairPrice: seagullParams.repairPrice,
                    },
                    {
                        id: 5,
                        name: "Наглый альбатрос",
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 300,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 13,
                        optima: 300,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 13,
                        [HEADING.MAX_VALUE]: 600,
                        minBuyPrice: 8,
                        minSellPrice: 12,
                        maxBuyPrice: 12,
                        maxSellPrice: 15,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 400,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 400,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 800,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 4,
                        [HEADING.SELL_PRICE]: 5,
                        optima: 250,
                        optimaBuyPrice: 4,
                        optimaSellPrice: 5,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 4,
                        maxBuyPrice: 5,
                        maxSellPrice: 6,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 250,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 50,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 50,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description: "",
            },
            {
                id: "start-02",
                name: "Дальний берег",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: "Хромая чайка",
                        velocity: seagullParams.velocity,
                        angularVelocity: seagullParams.angularVelocity,
                        damage: seagullParams.damage,
                        type: "seagull",
                        maxHealth: seagullParams.maxHealth,
                        currentHealth: seagullParams.currentHealth,
                        maxFuel: seagullParams.maxFuel,
                        currentFuel: seagullParams.maxFuel,
                        price: seagullParams.price,
                        repairPrice: seagullParams.repairPrice,
                    },
                    {
                        id: 5,
                        name: "Наглый альбатрос",
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 300,
                        [HEADING.BUY_PRICE]: 18,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 300,
                        optimaBuyPrice: 18,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 600,
                        minBuyPrice: 16,
                        minSellPrice: 24,
                        maxBuyPrice: 20,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 33,
                        optima: 250,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 33,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 29,
                        minSellPrice: 32,
                        maxBuyPrice: 36,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 23,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 14,
                        minSellPrice: 21,
                        maxBuyPrice: 18,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 250,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 4,
                        [HEADING.SELL_PRICE]: 5,
                        optima: 250,
                        optimaBuyPrice: 4,
                        optimaSellPrice: 5,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 3,
                        minSellPrice: 4,
                        maxBuyPrice: 5,
                        maxSellPrice: 6,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 250,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 250,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 50,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 50,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 50,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 100,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description: "",
            },
            {
                id: "middle",
                name: "Мидлгард",
                color: "green",
                ships: [
                    {
                        id: 5,
                        name: "Наглый альбатрос",
                        velocity: albatrossParams.velocity,
                        angularVelocity: albatrossParams.angularVelocity,
                        damage: albatrossParams.damage,
                        type: "albatross",
                        maxHealth: albatrossParams.maxHealth,
                        currentHealth: albatrossParams.currentHealth,
                        maxFuel: albatrossParams.maxFuel,
                        currentFuel: albatrossParams.currentFuel,
                        price: albatrossParams.price,
                        repairPrice: albatrossParams.repairPrice,
                    },
                    {
                        id: 6,
                        name: "Золотой пеликан",
                        velocity: pelicanParams.velocity,
                        angularVelocity: pelicanParams.angularVelocity,
                        damage: pelicanParams.damage,
                        type: "pelican",
                        maxHealth: pelicanParams.maxHealth,
                        currentHealth: pelicanParams.currentHealth,
                        maxFuel: pelicanParams.maxFuel,
                        currentFuel: pelicanParams.currentFuel,
                        price: pelicanParams.price,
                        repairPrice: pelicanParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 13,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 13,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 8,
                        minSellPrice: 12,
                        maxBuyPrice: 12,
                        maxSellPrice: 15,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 500,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 700,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 700,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 1400,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 600,
                        [HEADING.BUY_PRICE]: 5,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 600,
                        optimaBuyPrice: 5,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 1200,
                        minBuyPrice: 3,
                        minSellPrice: 6,
                        maxBuyPrice: 6,
                        maxSellPrice: 10,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 11,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 9,
                        minSellPrice: 10,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 16,
                        optima: 500,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 14,
                        minSellPrice: 19,
                        maxBuyPrice: 16,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 500,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 500,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 500,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 500,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 100,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 100,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description: "",
            },
            {
                id: "final-01",
                name: "Нордвиль",
                color: "deep-orange",
                ships: [
                    {
                        id: 6,
                        name: "Золотой пеликан",
                        velocity: pelicanParams.velocity,
                        angularVelocity: pelicanParams.angularVelocity,
                        damage: pelicanParams.damage,
                        type: "pelican",
                        maxHealth: pelicanParams.maxHealth,
                        currentHealth: pelicanParams.currentHealth,
                        maxFuel: pelicanParams.maxFuel,
                        currentFuel: pelicanParams.currentFuel,
                        price: pelicanParams.price,
                        repairPrice: pelicanParams.repairPrice,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 1000,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 18,
                        minSellPrice: 22,
                        maxBuyPrice: 22,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 25,
                        [HEADING.SELL_PRICE]: 35,
                        optima: 1000,
                        optimaBuyPrice: 25,
                        optimaSellPrice: 35,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 20,
                        minSellPrice: 30,
                        maxBuyPrice: 30,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 22,
                        optima: 500,
                        optimaBuyPrice: 9,
                        optimaSellPrice: 10,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 5,
                        minSellPrice: 6,
                        maxBuyPrice: 10,
                        maxSellPrice: 11,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 1200,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1200,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 2400,
                        minBuyPrice: 12,
                        minSellPrice: 16,
                        maxBuyPrice: 15,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 11,
                        optima: 1000,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 11,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 9,
                        minSellPrice: 10,
                        maxBuyPrice: 11,
                        maxSellPrice: 12,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 7,
                        [HEADING.SELL_PRICE]: 8,
                        optima: 1000,
                        optimaBuyPrice: 7,
                        optimaSellPrice: 8,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 6,
                        minSellPrice: 7,
                        maxBuyPrice: 8,
                        maxSellPrice: 9,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 1000,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 1000,
                        optimaBuyPrice: 16,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 10,
                        minSellPrice: 20,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 12,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1000,
                        optimaBuyPrice: 12,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 8,
                        minSellPrice: 14,
                        maxBuyPrice: 14,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 50,
                        optima: 1000,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 50,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 36,
                        minSellPrice: 48,
                        maxBuyPrice: 48,
                        maxSellPrice: 62,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 40,
                        optima: 250,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 40,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 25,
                        minSellPrice: 35,
                        maxBuyPrice: 35,
                        maxSellPrice: 45,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 250,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 250,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 18,
                        [HEADING.MAX_VALUE]: 500,
                        minBuyPrice: 8,
                        minSellPrice: 15,
                        maxBuyPrice: 15,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                ],
                description: "",
            },
            {
                id: "final-02",
                name: "Южный кит",
                color: "orange",
                ships: [
                    {
                        id: 7,
                        name: "Небесный кит",
                        velocity: whaleParams.velocity,
                        angularVelocity: whaleParams.angularVelocity,
                        damage: whaleParams.damage,
                        type: "whale",
                        maxHealth: whaleParams.maxHealth,
                        currentHealth: whaleParams.currentHealth,
                        maxFuel: whaleParams.maxFuel,
                        currentFuel: whaleParams.currentFuel,
                        price: whaleParams.price,
                        repairPrice: 8,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 26,
                        optima: 1000,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 26,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 18,
                        minSellPrice: 22,
                        maxBuyPrice: 22,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 25,
                        [HEADING.SELL_PRICE]: 35,
                        optima: 1000,
                        optimaBuyPrice: 25,
                        optimaSellPrice: 35,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 20,
                        minSellPrice: 30,
                        maxBuyPrice: 30,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 1000,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 33,
                        optima: 1000,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 33,
                        [HEADING.MAX_VALUE]: 2000,
                        minBuyPrice: 29,
                        minSellPrice: 32,
                        maxBuyPrice: 36,
                        maxSellPrice: 40,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 1200,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 18,
                        optima: 1200,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 2400,
                        minBuyPrice: 12,
                        minSellPrice: 16,
                        maxBuyPrice: 15,
                        maxSellPrice: 28,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 500,
                        [HEADING.BUY_PRICE]: 40,
                        [HEADING.SELL_PRICE]: 44,
                        optima: 500,
                        optimaBuyPrice: 40,
                        optimaSellPrice: 44,
                        [HEADING.MAX_VALUE]: 1000,
                        minBuyPrice: 32,
                        minSellPrice: 40,
                        maxBuyPrice: 44,
                        maxSellPrice: 48,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 750,
                        [HEADING.BUY_PRICE]: 15,
                        [HEADING.SELL_PRICE]: 16,
                        optima: 750,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 1500,
                        minBuyPrice: 14,
                        minSellPrice: 19,
                        maxBuyPrice: 16,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 750,
                        [HEADING.BUY_PRICE]: 10,
                        [HEADING.SELL_PRICE]: 15,
                        optima: 750,
                        optimaBuyPrice: 10,
                        optimaSellPrice: 15,
                        [HEADING.MAX_VALUE]: 1500,
                        minBuyPrice: 9,
                        minSellPrice: 14,
                        maxBuyPrice: 15,
                        maxSellPrice: 20,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 1500,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 1500,
                        optimaBuyPrice: 15,
                        optimaSellPrice: 20,
                        [HEADING.MAX_VALUE]: 3000,
                        minBuyPrice: 10,
                        minSellPrice: 19,
                        maxBuyPrice: 20,
                        maxSellPrice: 25,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 2000,
                        [HEADING.BUY_PRICE]: 6,
                        [HEADING.SELL_PRICE]: 9,
                        optima: 2000,
                        optimaBuyPrice: 6,
                        optimaSellPrice: 9,
                        [HEADING.MAX_VALUE]: 4000,
                        minBuyPrice: 4,
                        minSellPrice: 7,
                        maxBuyPrice: 7,
                        maxSellPrice: 11,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 1500,
                        [HEADING.BUY_PRICE]: 20,
                        [HEADING.SELL_PRICE]: 25,
                        optima: 1500,
                        optimaBuyPrice: 20,
                        optimaSellPrice: 25,
                        [HEADING.MAX_VALUE]: 3000,
                        minBuyPrice: 18,
                        minSellPrice: 24,
                        maxBuyPrice: 24,
                        maxSellPrice: 30,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 60,
                        [HEADING.SELL_PRICE]: 80,
                        optima: 100,
                        optimaBuyPrice: 60,
                        optimaSellPrice: 80,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 50,
                        minSellPrice: 70,
                        maxBuyPrice: 70,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 100,
                        [HEADING.BUY_PRICE]: 30,
                        [HEADING.SELL_PRICE]: 46,
                        optima: 100,
                        optimaBuyPrice: 30,
                        optimaSellPrice: 46,
                        [HEADING.MAX_VALUE]: 200,
                        minBuyPrice: 30,
                        minSellPrice: 39,
                        maxBuyPrice: 42,
                        maxSellPrice: 90,
                        isGrow: true,
                    },
                ],
                description: "",
            },
        ],
        isShowSinkAlert: false,
    }),
    getters: {
        currentTown: (state): Town => {
            return state.towns.find((town) => town.id === state.currentTownId) as Town
        },
    },
    actions: {
        setTown(name: string): void {
            this.currentTownId = name
        },
        setCoords(coords: Coords): void {
            this.coords = coords
        },
        setShowSinkAlert(value: boolean) {
            this.isShowSinkAlert = value
        },
        decreaseCurrentTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] -= amount
        },
        increaseCurrentTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] += amount
        },
        increaseTownResource(townId: string, key: string, amount: number) {
            const town = this.towns.find((town) => town.id === townId) as Town
            const resource = town.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] += amount
            resource.isGrow = true
        },
        decreaseTownResource(townId: string, key: string, amount: number) {
            const town = this.towns.find((town) => town.id === townId) as Town
            const resource = town.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] -= amount
            resource.isGrow = resource[HEADING.VALUE] <= resource.optima
        },
        calculatePrice(resource: ResourceTable) {
            const difference = resource.optima - resource[HEADING.VALUE]
            const percentValue = difference / (resource.optima / 100)
            const percentBuyPrice = resource.optimaBuyPrice / 100
            const percentSellPrice = resource.optimaSellPrice / 100
            let newBuyPrice = resource[HEADING.BUY_PRICE]
            let newSellPrice = resource[HEADING.BUY_PRICE]
            if (resource[HEADING.VALUE] < resource.optima) {
                newBuyPrice = Math.floor(resource.optimaBuyPrice + Math.abs(percentValue) * percentBuyPrice)
                newSellPrice = Math.floor(resource.optimaSellPrice + Math.abs(percentValue) * percentSellPrice)
            } else {
                newBuyPrice = Math.floor(resource.optimaBuyPrice - Math.abs(percentValue) * percentBuyPrice)
                newSellPrice = Math.floor(resource.optimaSellPrice - Math.abs(percentValue) * percentSellPrice)
            }

            if (newBuyPrice > resource.maxBuyPrice) {
                resource[HEADING.BUY_PRICE] = resource.maxBuyPrice
            } else if (newBuyPrice < resource.minBuyPrice) {
                resource[HEADING.BUY_PRICE] = resource.minBuyPrice
            } else {
                resource[HEADING.BUY_PRICE] = newBuyPrice
            }

            if (newSellPrice > resource.maxSellPrice) {
                resource[HEADING.SELL_PRICE] = resource.maxSellPrice
            } else if (newSellPrice < resource.minSellPrice) {
                resource[HEADING.SELL_PRICE] = resource.minSellPrice
            } else {
                resource[HEADING.SELL_PRICE] = newSellPrice
            }
        },
    },
})
