import { defineStore } from "pinia"
import { Coords, HEADING, ResourceTable, Town, TownStore } from "../types/interfaces.ts"
import { BASIC_SHIP_ANGULAR_VELOCITY, BASIC_SHIP_SPEED } from "../configs/gameplay.config.ts"

export const useTown = defineStore("town", {
    state: (): TownStore => ({
        currentTownId: "start-01",
        coords: {
            x: 1280,
            y: 1280,
        },
        towns: [
            {
                id: "start-01",
                name: "start-01",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: "Хромая чайка",
                        velocity: BASIC_SHIP_SPEED,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY + 80,
                        damage: 5,
                        type: "seagull",
                        maxHealth: 20,
                        currentHealth: 18,
                        maxFuel: 50,
                        currentFuel: 20,
                        price: 100,
                        repairPrice: 1,
                    },
                    {
                        id: 5,
                        name: "Наглый альбатрос",
                        velocity: BASIC_SHIP_SPEED + 80,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY + 30,
                        damage: 20,
                        type: "albatross",
                        maxHealth: 100,
                        currentHealth: 100,
                        maxFuel: 120,
                        currentFuel: 100,
                        price: 1000,
                        repairPrice: 3,
                    },
                    {
                        id: 6,
                        name: "Золотой пеликан",
                        velocity: BASIC_SHIP_SPEED + 120,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY - 30,
                        damage: 50,
                        type: "pelican",
                        maxHealth: 300,
                        currentHealth: 300,
                        maxFuel: 500,
                        currentFuel: 200,
                        price: 5000,
                        repairPrice: 5,
                    },
                    {
                        id: 7,
                        name: "Небесный кит",
                        velocity: BASIC_SHIP_SPEED + 150,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY - 30,
                        damage: 100,
                        type: "whale",
                        maxHealth: 700,
                        currentHealth: 600,
                        maxFuel: 900,
                        currentFuel: 900,
                        price: 15000,
                        repairPrice: 8,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                ],
            },
            {
                id: "start-02",
                name: "start-02",
                color: "green",
                ships: [
                    {
                        id: 4,
                        name: "Хромая чайка",
                        velocity: BASIC_SHIP_SPEED,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY + 80,
                        damage: 5,
                        type: "seagull",
                        maxHealth: 20,
                        currentHealth: 18,
                        maxFuel: 50,
                        currentFuel: 20,
                        price: 100,
                        repairPrice: 1,
                    },
                    {
                        id: 5,
                        name: "Наглый альбатрос",
                        velocity: BASIC_SHIP_SPEED + 80,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY + 30,
                        damage: 20,
                        type: "albatross",
                        maxHealth: 100,
                        currentHealth: 100,
                        maxFuel: 120,
                        currentFuel: 100,
                        price: 1000,
                        repairPrice: 3,
                    },
                    {
                        id: 6,
                        name: "Золотой пеликан",
                        velocity: BASIC_SHIP_SPEED + 120,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY - 30,
                        damage: 50,
                        type: "pelican",
                        maxHealth: 300,
                        currentHealth: 300,
                        maxFuel: 500,
                        currentFuel: 200,
                        price: 5000,
                        repairPrice: 5,
                    },
                    {
                        id: 7,
                        name: "Небесный кит",
                        velocity: BASIC_SHIP_SPEED + 150,
                        angularVelocity: BASIC_SHIP_ANGULAR_VELOCITY - 30,
                        damage: 100,
                        type: "whale",
                        maxHealth: 700,
                        currentHealth: 600,
                        maxFuel: 900,
                        currentFuel: 900,
                        price: 15000,
                        repairPrice: 8,
                    },
                ],
                resources: [
                    {
                        [HEADING.NAME]: "Сахарный тростник",
                        key: "sugar",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Кукуруза",
                        key: "corn",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Пряности",
                        key: "spice",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Зерно",
                        key: "grain",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Древесина",
                        key: "wood",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Конопля",
                        key: "hemp",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Хлопок",
                        key: "cotton",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Порох",
                        key: "gunpowder",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Уголь",
                        key: "coal",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Сталь",
                        key: "steel",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Слоновая кость",
                        key: "ivory",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                    {
                        [HEADING.NAME]: "Шелк",
                        key: "silk",
                        [HEADING.VALUE]: 262,
                        [HEADING.BUY_PRICE]: 16,
                        [HEADING.SELL_PRICE]: 23,
                        optima: 262,
                        optimaPrice: 16,
                        maxValue: 500,
                        minBuyPrice: 10,
                        minSellPrice: 13,
                        maxBuyPrice: 26,
                        maxSellPrice: 36,
                    },
                ],
            },
        ],
        isShowSinkAlert: false,
    }),
    getters: {
        currentTown: (state): Town => {
            return state.towns.find((town) => town.id === state.currentTownId) as Town
        },
    },
    actions: {
        setTown(name: string): void {
            this.currentTownId = name
        },
        setCoords(coords: Coords): void {
            this.coords = coords
        },
        setShowSinkAlert(value: boolean) {
            this.isShowSinkAlert = value
        },
        decreaseTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] -= amount
        },
        increaseTownResource(key: string, amount: number) {
            const resource = this.currentTown.resources.find((resource) => resource.key === key) as ResourceTable
            resource[HEADING.VALUE] += amount
        },
        calculatePrice(resource: ResourceTable) {
            console.log("calculatePrice", resource)
        },
    },
})
